[2021-09-27 15:30:02,933] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.echo_hello 2021-09-27T15:20:00+00:00 [queued]>
[2021-09-27 15:30:02,985] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.echo_hello 2021-09-27T15:20:00+00:00 [queued]>
[2021-09-27 15:30:02,988] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 15:30:02,989] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-27 15:30:02,990] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 15:30:03,032] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): echo_hello> on 2021-09-27T15:20:00+00:00
[2021-09-27 15:30:03,046] {standard_task_runner.py:52} INFO - Started process 27478 to run task
[2021-09-27 15:30:03,077] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'echo_hello', '2021-09-27T15:20:00+00:00', '--job-id', '94', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbbydphup', '--error-file', '/tmp/tmpranfn85i']
[2021-09-27 15:30:03,098] {standard_task_runner.py:77} INFO - Job 94: Subtask echo_hello
[2021-09-27 15:30:03,505] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.echo_hello 2021-09-27T15:20:00+00:00 [running]> on host 196580edc338
[2021-09-27 15:30:03,941] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Attasil Chitwirote
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=echo_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-27T15:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-27T15:20:00+00:00
[2021-09-27 15:30:03,944] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-09-27 15:30:03,946] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'hello'"]
[2021-09-27 15:30:03,978] {subprocess.py:74} INFO - Output:
[2021-09-27 15:30:03,987] {subprocess.py:78} INFO - hello
[2021-09-27 15:30:03,989] {subprocess.py:82} INFO - Command exited with return code 0
[2021-09-27 15:30:04,037] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=echo_hello, execution_date=20210927T152000, start_date=20210927T153002, end_date=20210927T153004
[2021-09-27 15:30:04,111] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-27 15:30:04,147] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
